### ISSUE TITLE
Different iterator instructions reported in seemingly identical loops

### ISSUE THREAD

**Issue by robcasloz** [compor/IteratorRecognition#1]
Hi Chris, thanks for the effort you put maintaining this library :)

In a simple single-loop function, the iterator recognition pass reports different LLVM IR instructions as belonging to the loop's iterator depending on whether the function returns:
```
void foo() {
  int i;
  for (i = 0; i < N; i++) {}
  return;
}
```
or exits:
```
void foo() {
  int i;
  for (i = 0; i < N; i++) {}
  exit(0);
}
```
The loops are identical in both cases, so I would expect the same instructions to be reported.

**How to reproduce**

1. Run `clang -emit-llvm -S foo.c -o foo.ll` (`foo.c` is available here: [foo.c.zip](https://github.com/compor/IteratorRecognition/files/3234487/foo.c.zip)).
2. Run `opt -itr-annotate -S foo.ll -o foo-itr.ll`.
3. Assert that `grep "iterator \!2" foo-itr.ll` and `grep "iterator \!3" foo-itr.ll` produce the same output. Currently, this step fails.

Thank you for your time! Let me know if I can help in any way.

**Comment by compor** [comment]
Hey!

This is a quick response, but I'll look into it in depth later today.

So, without having a look at the attached files, I'd say that the IR generated is different because of [`exit()`][2], which is known to terminate the program wherever/whenever it is called. In IR terms we'd get an [`unreachable`][1] terminator instruction.  I'm not sure how that affects the analysis without a further look.

[1]: https://llvm.org/docs/LangRef.html#unreachable-instruction
[2]: https://en.cppreference.com/w/cpp/utility/program/exit

**Comment by compor** [comment]
A short update: It seems that the control dependence graph (CDG) generated for `bar()` (which uses `exit()`) is empty, which most likely means that the specific terminator instruction type (i.e. `unreachable`) is not handled.

**Comment by compor** [comment]
@robcasloz This was an issue with Pedigree, so I opened an issue for it [here][1] and it is hopefully address in the referenced PR.

Please try it and let me know.

[1]: https://github.com/compor/Pedigree/issues/1

**Comment by robcasloz** [comment]
Hi @compor, I tried the PR and it works just fine, now the same instructions are reported as iterators in both cases. Thanks!

**Comment by compor** [comment]
Cool! I'm closing this since it was addressed [here][1].
Thanks for catching this and all the feedback! :smile:

[1]: https://github.com/compor/Pedigree/pull/2
